/**
 * フィールドの条件付き表示判定
 */
export function shouldShowField(field, vals) {
  if (!field.showIf) return true
  if (field.showIf.includes(':')) {
    const [k, expected] = field.showIf.split(':')
    return String(vals[k]) === expected
  }
  return !!vals[field.showIf]
}

/**
 * デフォルトグローバルカラー
 */
export const DEFAULT_GLOBAL_COLOR = {
  primary: '#2563eb',
  accent: '#00d4aa',
  bg: '#0a0f1e',
  bgLight: '#ffffff',
  textDark: '#1a1a1a',
  textLight: '#ffffff',
}

/**
 * パーツのrender出力から <style> と HTML を分離する
 */
function separateStyleAndHTML(rendered) {
  const styleRegex = /<style>([\s\S]*?)<\/style>/gi
  let css = ''
  let match
  while ((match = styleRegex.exec(rendered)) !== null) {
    css += match[1] + '\n'
  }
  const html = rendered.replace(styleRegex, '').trim()
  return { css, html }
}

/**
 * グローバルCSS生成
 */
function generateGlobalCSS(globalColor) {
  return `/* ============================================================
   Global Styles
   Generated by Site Builder
   ============================================================ */

/* Reset */
*, *::before, *::after {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
}

body {
  overflow-x: hidden;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

img {
  max-width: 100%;
  height: auto;
  display: block;
}

a {
  color: inherit;
}

/* CSS Variables */
:root {
  --color-primary: ${globalColor.primary};
  --color-accent: ${globalColor.accent};
  --color-bg-dark: ${globalColor.bg};
  --color-bg-light: ${globalColor.bgLight};
  --color-text-dark: ${globalColor.textDark};
  --color-text-light: ${globalColor.textLight};
  --font-main: 'Noto Sans JP', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
}
`
}

/**
 * JS生成（FAQ開閉など）
 */
function generateJS() {
  return `/* ============================================================
   Site Scripts
   Generated by Site Builder
   ============================================================ */

// Smooth scroll for anchor links
document.querySelectorAll('a[href^="#"]').forEach(anchor => {
  anchor.addEventListener('click', function (e) {
    const target = document.querySelector(this.getAttribute('href'));
    if (target) {
      e.preventDefault();
      target.scrollIntoView({ behavior: 'smooth' });
    }
  });
});

// Intersection Observer for scroll animations (optional)
const observerOptions = { threshold: 0.1, rootMargin: '0px 0px -50px 0px' };
const observer = new IntersectionObserver((entries) => {
  entries.forEach(entry => {
    if (entry.isIntersecting) {
      entry.target.style.opacity = '1';
      entry.target.style.transform = 'translateY(0)';
    }
  });
}, observerOptions);

document.querySelectorAll('section').forEach(section => {
  section.style.opacity = '0';
  section.style.transform = 'translateY(20px)';
  section.style.transition = 'opacity 0.6s ease, transform 0.6s ease';
  observer.observe(section);
});

// Header elements don't need animation
document.querySelectorAll('header, footer').forEach(el => {
  el.style.opacity = '1';
  el.style.transform = 'none';
});
`
}

/**
 * 構造化された出力ファイルを生成
 * @returns {{ indexHTML: string, globalCSS: string, sectionsCSS: string, mainJS: string }}
 */
export function generateStructuredOutput(parts, vars, globalColor) {
  let allCSS = ''
  let allHTML = ''

  parts.forEach((p, i) => {
    const rendered = p.render(vars[p.iid], globalColor)
    const { css, html } = separateStyleAndHTML(rendered)
    allCSS += `/* --- ${p.name} (${p.category}) --- */\n${css}\n`
    allHTML += `\n  <!-- ${p.category}: ${p.name} -->\n  ${html}\n`
  })

  const globalCSS = generateGlobalCSS(globalColor)
  const sectionsCSS = `/* ============================================================\n   Section Styles\n   Generated by Site Builder\n   ============================================================ */\n\n${allCSS}`
  const mainJS = generateJS()

  const indexHTML = `<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Generated Site</title>

  <!-- Fonts -->
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@400;500;600;700;800;900&display=swap" rel="stylesheet">

  <!-- Styles -->
  <link rel="stylesheet" href="css/global.css">
  <link rel="stylesheet" href="css/sections.css">
</head>
<body>
${allHTML}
  <!-- Scripts -->
  <script src="js/main.js"><\/script>
</body>
</html>`

  return { indexHTML, globalCSS, sectionsCSS, mainJS }
}

/**
 * プレビュー用の単一HTML生成（従来通り）
 */
export function generateFullHTML(parts, vars, globalColor) {
  const sections = parts
    .map(p => p.render(vars[p.iid], globalColor))
    .join('\n')

  return `<!DOCTYPE html>
<html lang="ja">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1.0">
<title>Generated Site</title>
<link href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@400;500;600;700;800;900&display=swap" rel="stylesheet">
<style>*{margin:0;padding:0;box-sizing:border-box}body{overflow-x:hidden}</style>
</head>
<body>
${sections}
</body>
</html>`
}

/**
 * ZIP生成 & ダウンロード（軽量な自前実装、ライブラリ不要）
 */
export async function downloadAsZip(parts, vars, globalColor) {
  const { indexHTML, globalCSS, sectionsCSS, mainJS } = generateStructuredOutput(parts, vars, globalColor)

  // CRC32 table
  const crcTable = new Uint32Array(256)
  for (let i = 0; i < 256; i++) {
    let c = i
    for (let j = 0; j < 8; j++) c = c & 1 ? 0xEDB88320 ^ (c >>> 1) : c >>> 1
    crcTable[i] = c
  }
  const crc32 = (buf) => {
    let c = 0xFFFFFFFF
    for (let i = 0; i < buf.length; i++) c = crcTable[(c ^ buf[i]) & 0xFF] ^ (c >>> 8)
    return (c ^ 0xFFFFFFFF) >>> 0
  }

  const enc = new TextEncoder()
  const files = [
    { name: 'site/index.html', data: enc.encode(indexHTML) },
    { name: 'site/css/global.css', data: enc.encode(globalCSS) },
    { name: 'site/css/sections.css', data: enc.encode(sectionsCSS) },
    { name: 'site/js/main.js', data: enc.encode(mainJS) },
  ]

  // Build ZIP manually
  const localHeaders = []
  const centralHeaders = []
  let offset = 0

  for (const file of files) {
    const nameBytes = enc.encode(file.name)
    const crc = crc32(file.data)
    const size = file.data.length

    // Local file header (30 + name + data)
    const local = new Uint8Array(30 + nameBytes.length + size)
    const lv = new DataView(local.buffer)
    lv.setUint32(0, 0x04034b50, true) // sig
    lv.setUint16(4, 20, true) // version
    lv.setUint16(6, 0, true) // flags
    lv.setUint16(8, 0, true) // compression (store)
    lv.setUint16(10, 0, true) // mod time
    lv.setUint16(12, 0, true) // mod date
    lv.setUint32(14, crc, true)
    lv.setUint32(18, size, true) // compressed
    lv.setUint32(22, size, true) // uncompressed
    lv.setUint16(26, nameBytes.length, true)
    lv.setUint16(28, 0, true) // extra length
    local.set(nameBytes, 30)
    local.set(file.data, 30 + nameBytes.length)
    localHeaders.push(local)

    // Central directory header
    const central = new Uint8Array(46 + nameBytes.length)
    const cv = new DataView(central.buffer)
    cv.setUint32(0, 0x02014b50, true)
    cv.setUint16(4, 20, true)
    cv.setUint16(6, 20, true)
    cv.setUint16(8, 0, true)
    cv.setUint16(10, 0, true)
    cv.setUint16(12, 0, true)
    cv.setUint16(14, 0, true)
    cv.setUint32(16, crc, true)
    cv.setUint32(20, size, true)
    cv.setUint32(24, size, true)
    cv.setUint16(28, nameBytes.length, true)
    cv.setUint16(30, 0, true)
    cv.setUint16(32, 0, true)
    cv.setUint16(34, 0, true)
    cv.setUint16(36, 0, true)
    cv.setUint32(38, 32, true)
    cv.setUint32(42, offset, true)
    central.set(nameBytes, 46)
    centralHeaders.push(central)

    offset += local.length
  }

  const centralSize = centralHeaders.reduce((s, c) => s + c.length, 0)
  const eocd = new Uint8Array(22)
  const ev = new DataView(eocd.buffer)
  ev.setUint32(0, 0x06054b50, true)
  ev.setUint16(4, 0, true)
  ev.setUint16(6, 0, true)
  ev.setUint16(8, files.length, true)
  ev.setUint16(10, files.length, true)
  ev.setUint32(12, centralSize, true)
  ev.setUint32(16, offset, true)
  ev.setUint16(20, 0, true)

  const blob = new Blob([...localHeaders, ...centralHeaders, eocd], { type: 'application/zip' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = 'site.zip'
  a.click()
  URL.revokeObjectURL(url)
}

/**
 * 単一HTMLダウンロード（後方互換）
 */
export function downloadHTML(html, filename = 'site.html') {
  const blob = new Blob([html], { type: 'text/html' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  a.click()
  URL.revokeObjectURL(url)
}
